version: "3.8"
services:
  library-app:
    image: library:0.0.2
    container_name: library-app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:9999/library
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=01658582113
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql
    depends_on:
      - library-db
    networks:
      - library-network

volumes:
  library-db:

networks:
  library-network: